### ISSUE TITLE
Compilation is difficult

### ISSUE THREAD

**Issue by wwoods** [adamschmideg/coffeescript-eclipse#12]
Hey, I'm trying to make a pull request for coffeescript-eclipse that fixes the tabbing issue (e.g. uses spaces properly), but I cant get make.py to work. 

It keeps throwing a javac error:

javac: file not found: csep/src-gen/csep/parser/antlr/internal/InternalCoffeeScriptLexer.java
Usage: javac <options> <source files>
use -help for a list of possible options
Traceback (most recent call last):
  File "./make.py", line 127, in <module>
    main()
  File "./make.py", line 123, in main
    compile_grammar(jars, prj_name, prj_grammar)
  File "./make.py", line 95, in compile_grammar
    raise RuntimeError("Java failed")
RuntimeError: Java failed

Any help would be appreciated.  It seems like (and I can't see where it would be, so it makes sense) src-gen is never being populated.

Thanks!

**Comment by paulvi** [comment]
There was Nodeclipse/coffeescript-eclipse#23 and CSEP is already mavenzied. 0.4 is to be released this month.
